[workspace]
name = "dinrail"
description = "A lightweight library for robot device abstractions"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-arm64"]

[target.win.activation.env]
CMAKE_INSTALL_PREFIX = "%CONDA_PREFIX%\\Library"

[target.unix.activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[tasks]
configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX",
    "-DDINRAIL_BUILD_EXAMPLES:BOOL=ON",
    "-DDINRAIL_USES_YARP:BOOL=ON",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends-on = ["configure"] }
install = { cmd = ["cmake", "--install", ".build", "--config", "Release"], depends-on = ["build"] }
test = { cmd = "ctest --test-dir .build --build-config Release", depends-on = ["install"] }
uninstall = { cmd = ["cmake", "--build", ".build", "--target", "uninstall"] }

format = { cmd = "clang-format -i $(git ls-files '*.cpp' '*.h' '*.cxx' '*.hpp')" }

[dependencies]
cmake = "*"
cxx-compiler = "*"
ninja = "*"
pkg-config = "*"
ycm-cmake-modules = "*"
libsharedlibpp = "*"
clang-format = "*"
libyarp = "*"
libbipedal-locomotion-framework = "*"
catch2 = "*"
cli11 = "*"
