/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu May 22 11:32:44 2025

#include "DinRailControlBoardNWSYarp_ParamsParser.h"
#include "ControlBoardLogComponent.h"

#include <yarp/os/Value.h>

DinRailControlBoardNWSYarp_ParamsParser::DinRailControlBoardNWSYarp_ParamsParser()
{
}

std::vector<std::string> DinRailControlBoardNWSYarp_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("period");
    params.push_back("name");
    params.push_back("namesuffix");
    params.push_back("emulate_impedance_all_setpoints_control");
    return params;
}

bool DinRailControlBoardNWSYarp_ParamsParser::getParamValue(const std::string& paramName,
                                                            std::string& paramValue) const
{
    auto& logger = controlBoardLogger();

    if (paramName == "period")
    {
        paramValue = std::to_string(m_period);
        return true;
    }
    if (paramName == "name")
    {
        paramValue = m_name;
        return true;
    }
    if (paramName == "namesuffix")
    {
        paramValue = m_namesuffix;
        return true;
    }
    if (paramName == "emulate_impedance_all_setpoints_control")
    {
        paramValue = m_emulate_impedance_all_setpoints_control ? "true" : "false";
        return true;
    }

    logger.error("parameter '{}' was not found", paramName);
    return false;
}

std::string DinRailControlBoardNWSYarp_ParamsParser::getConfiguration() const
{
    // This is a sub-optimal solution.
    // Ideally getConfiguration() should return all parameters but it is currently
    // returning only user provided parameters (excluding default values)
    // This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool DinRailControlBoardNWSYarp_ParamsParser::parseParams(const yarp::os::Searchable& config)
{
    auto& logger = controlBoardLogger();

    // Check for --help option
    if (config.check("help"))
    {
        logger.info("{}", getDocumentationOfDeviceParams());
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    // Parser of parameter period
    {
        if (config.check("period"))
        {
            m_period = config.find("period").asFloat64();
            logger.info("Parameter 'period' using value: {}", m_period);
        } else
        {
            logger.info("Parameter 'period' using DEFAULT value: {}", m_period);
        }
        prop_check.unput("period");
    }

    // Parser of parameter name
    {
        if (config.check("name"))
        {
            m_name = config.find("name").asString();
            logger.info("Parameter 'name' using value: {}", m_name);
        } else
        {
            logger.error("Mandatory parameter 'name' not found!");
            logger.error("Description of the parameter: Prefix name of the ports opened by the "
                         "device");
            return false;
        }
        prop_check.unput("name");
    }

    // Parser of parameter namesuffix
    {
        if (config.check("namesuffix"))
        {
            m_namesuffix = config.find("namesuffix").asString();
            logger.info("Parameter 'namesuffix' using value: {}", m_namesuffix);
        } else
        {
            logger.info("Parameter 'namesuffix' using DEFAULT value: {}", m_namesuffix);
        }
        prop_check.unput("namesuffix");
    }

    // Parser of parameter emulate_impedance_all_setpoints_control
    {
        if (config.check("emulate_impedance_all_setpoints_control"))
        {
            m_emulate_impedance_all_setpoints_control
                = config.find("emulate_impedance_all_setpoints_control").asBool();
            logger.info("Parameter 'emulate_impedance_all_setpoints_control' using value: {}",
                        m_emulate_impedance_all_setpoints_control);
        } else
        {
            logger.info("Parameter 'emulate_impedance_all_setpoints_control' using DEFAULT value: "
                        "{}",
                        m_emulate_impedance_all_setpoints_control);
        }
        prop_check.unput("emulate_impedance_all_setpoints_control");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                logger.error("User asking for parameter: {} which is unknown to this parser!",
    it->name); extra_params_found = true;
            }
            else
            {
                logger.warn("User asking for parameter: {} which is unknown to this parser!",
    it->name);
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}

std::string DinRailControlBoardNWSYarp_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: DinRailControlBoardNWSYarp\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'period': period of the main thread\n");
    doc = doc + std::string("'name': Prefix name of the ports opened by the device\n");
    doc = doc + std::string("'namesuffix': Suffix appended to the base port prefix\n");
    doc = doc
          + std::string("'emulate_impedance_all_setpoints_control': Emulate dinrail "
                        "IImpedanceAllSetPointsControl if subdevice does not expose it\n");
    doc = doc + std::string("\n");
    doc = doc
          + std::string("Here are some examples of invocation command with yarpdev, with all "
                        "params:\n");
    doc = doc
          + " yarpdev --device controlBoard_nws_yarp --period 0.02 --name /robot/part --namesuffix "
            "/dinrail --emulate_impedance_all_setpoints_control false\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device controlBoard_nws_yarp --name /robot/part\n";
    doc = doc + std::string("=============================================\n\n");
    return doc;
}
