/*
 * SPDX-FileCopyrightText: Generative Bionics S.R.L.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef DINRAIL_CONTROLBOARD_YARP_PROTOCOLVERSION_H
#define DINRAIL_CONTROLBOARD_YARP_PROTOCOLVERSION_H

namespace dinrail
{

constexpr int CONTROLBOARD_YARP_PROTOCOL_VERSION_MAJOR = 1;
constexpr int CONTROLBOARD_YARP_PROTOCOL_VERSION_MINOR = 9;
constexpr int CONTROLBOARD_YARP_PROTOCOL_VERSION_TWEAK = 0;

}

#endif // DINRAIL_CONTROLBOARD_YARP_PROTOCOLVERSION_H
